"""Demo NEET question seed data - handcrafted representative questions across P/C/B."""
from datetime import datetime, timezone
import uuid
import random

_CHAPTERS = {
    "Physics": [
        "Kinematics", "Laws of Motion", "Work Energy Power", "Rotational Motion",
        "Gravitation", "Thermodynamics", "Oscillations", "Waves",
        "Electrostatics", "Current Electricity", "Magnetism", "EMI & AC",
        "Ray Optics", "Wave Optics", "Modern Physics", "Semiconductors",
    ],
    "Chemistry": [
        "Atomic Structure", "Chemical Bonding", "States of Matter", "Thermodynamics",
        "Equilibrium", "Redox Reactions", "Solutions", "Electrochemistry",
        "Chemical Kinetics", "Surface Chemistry", "P-block Elements", "D & F block",
        "Coordination Compounds", "Haloalkanes", "Alcohols Phenols Ethers", "Biomolecules",
    ],
    "Biology": [
        "Cell: The Unit of Life", "Biomolecules", "Cell Cycle & Division",
        "Plant Kingdom", "Animal Kingdom", "Morphology of Plants",
        "Human Physiology - Digestion", "Human Physiology - Respiration",
        "Human Physiology - Circulation", "Neural Control",
        "Reproduction in Organisms", "Human Reproduction",
        "Genetics & Evolution", "Human Health & Disease",
        "Ecology & Environment", "Biotechnology",
    ],
}

# A curated pool of high-quality NEET questions (~30 per subject).
_QUESTIONS = [
    # ---------- Physics ----------
    {"subject":"Physics","chapter":"Kinematics","topic":"1D motion","difficulty":"Easy","q_type":"Numerical",
     "text":"A body moves with uniform acceleration and covers 40 m in the 4th second. If its initial velocity is 5 m/s, find its acceleration.",
     "options":[{"key":"A","text":"5 m/s²"},{"key":"B","text":"10 m/s²"},{"key":"C","text":"20 m/s²"},{"key":"D","text":"2.5 m/s²"}],
     "correct_key":"B","explanation":"Distance in nth second sn = u + a(2n-1)/2. 40 = 5 + a(7)/2 → a=10 m/s²."},
    {"subject":"Physics","chapter":"Laws of Motion","topic":"Friction","difficulty":"Medium","q_type":"Numerical",
     "text":"A 10 kg block rests on a rough surface (μ=0.3). Minimum horizontal force required to just move it? (g=10)",
     "options":[{"key":"A","text":"20 N"},{"key":"B","text":"30 N"},{"key":"C","text":"50 N"},{"key":"D","text":"100 N"}],
     "correct_key":"B","explanation":"F_min = μ·mg = 0.3·10·10 = 30 N."},
    {"subject":"Physics","chapter":"Work Energy Power","topic":"KE","difficulty":"Easy","q_type":"Theoretical",
     "text":"If the momentum of a body is doubled, its kinetic energy becomes:",
     "options":[{"key":"A","text":"Doubled"},{"key":"B","text":"Halved"},{"key":"C","text":"Four times"},{"key":"D","text":"Unchanged"}],
     "correct_key":"C","explanation":"KE = p²/2m, so doubling p quadruples KE."},
    {"subject":"Physics","chapter":"Rotational Motion","topic":"Moment of inertia","difficulty":"Medium","q_type":"Theoretical",
     "text":"The moment of inertia of a uniform disc of mass M and radius R about an axis through its center perpendicular to its plane is:",
     "options":[{"key":"A","text":"MR²"},{"key":"B","text":"MR²/2"},{"key":"C","text":"MR²/4"},{"key":"D","text":"2MR²/5"}],
     "correct_key":"B","explanation":"For a disc, I = (1/2)MR²."},
    {"subject":"Physics","chapter":"Gravitation","topic":"Orbital velocity","difficulty":"Medium","q_type":"Theoretical",
     "text":"The escape velocity from Earth's surface is approximately:",
     "options":[{"key":"A","text":"7.9 km/s"},{"key":"B","text":"11.2 km/s"},{"key":"C","text":"9.8 km/s"},{"key":"D","text":"15 km/s"}],
     "correct_key":"B","explanation":"v_esc = √(2gR) ≈ 11.2 km/s at Earth surface."},
    {"subject":"Physics","chapter":"Thermodynamics","topic":"First law","difficulty":"Easy","q_type":"Theoretical",
     "text":"In an isothermal process for an ideal gas:",
     "options":[{"key":"A","text":"ΔU = 0"},{"key":"B","text":"ΔQ = 0"},{"key":"C","text":"ΔW = 0"},{"key":"D","text":"ΔS = 0"}],
     "correct_key":"A","explanation":"Isothermal ⇒ ΔT=0 ⇒ ΔU=0 for ideal gas. Heat added equals work done."},
    {"subject":"Physics","chapter":"Oscillations","topic":"SHM","difficulty":"Medium","q_type":"Numerical",
     "text":"A particle in SHM has amplitude 0.1 m and angular frequency 10 rad/s. Its maximum velocity is:",
     "options":[{"key":"A","text":"0.1 m/s"},{"key":"B","text":"1 m/s"},{"key":"C","text":"10 m/s"},{"key":"D","text":"100 m/s"}],
     "correct_key":"B","explanation":"v_max = Aω = 0.1×10 = 1 m/s."},
    {"subject":"Physics","chapter":"Waves","topic":"Sound","difficulty":"Easy","q_type":"Theoretical",
     "text":"The speed of sound in air is nearly:",
     "options":[{"key":"A","text":"330 m/s"},{"key":"B","text":"1500 m/s"},{"key":"C","text":"3×10⁸ m/s"},{"key":"D","text":"1130 m/s"}],
     "correct_key":"A","explanation":"Speed of sound in air ≈ 330-340 m/s at room temperature."},
    {"subject":"Physics","chapter":"Electrostatics","topic":"Coulomb law","difficulty":"Hard","q_type":"Numerical",
     "text":"Two charges +2μC and +3μC are 30 cm apart. Force between them (k=9×10⁹) is:",
     "options":[{"key":"A","text":"0.6 N"},{"key":"B","text":"0.06 N"},{"key":"C","text":"6 N"},{"key":"D","text":"60 N"}],
     "correct_key":"A","explanation":"F=kq1q2/r²=9e9·6e-12/0.09=0.6 N."},
    {"subject":"Physics","chapter":"Current Electricity","topic":"Ohm's law","difficulty":"Easy","q_type":"Numerical",
     "text":"A 12V battery drives 2 A through a resistor. Its resistance is:",
     "options":[{"key":"A","text":"6 Ω"},{"key":"B","text":"24 Ω"},{"key":"C","text":"4 Ω"},{"key":"D","text":"14 Ω"}],
     "correct_key":"A","explanation":"R=V/I=12/2=6 Ω."},
    {"subject":"Physics","chapter":"Magnetism","topic":"Force on wire","difficulty":"Medium","q_type":"Numerical",
     "text":"A wire carrying 5 A of length 0.4 m is placed perpendicular to a 0.2 T field. Force on it is:",
     "options":[{"key":"A","text":"0.2 N"},{"key":"B","text":"0.4 N"},{"key":"C","text":"1 N"},{"key":"D","text":"4 N"}],
     "correct_key":"B","explanation":"F=BIL=0.2·5·0.4=0.4 N."},
    {"subject":"Physics","chapter":"EMI & AC","topic":"Faraday","difficulty":"Medium","q_type":"Theoretical",
     "text":"Lenz's law is a consequence of conservation of:",
     "options":[{"key":"A","text":"Charge"},{"key":"B","text":"Energy"},{"key":"C","text":"Momentum"},{"key":"D","text":"Angular momentum"}],
     "correct_key":"B","explanation":"Induced current opposes the change to conserve energy."},
    {"subject":"Physics","chapter":"Ray Optics","topic":"Lens","difficulty":"Easy","q_type":"Numerical",
     "text":"Power of a lens of focal length +50 cm is:",
     "options":[{"key":"A","text":"+0.5 D"},{"key":"B","text":"+2 D"},{"key":"C","text":"+5 D"},{"key":"D","text":"+50 D"}],
     "correct_key":"B","explanation":"P=1/f(m)=1/0.5=+2 D."},
    {"subject":"Physics","chapter":"Wave Optics","topic":"Interference","difficulty":"Hard","q_type":"Theoretical",
     "text":"In Young's double-slit experiment, if the entire setup is immersed in water (n=4/3), the fringe width:",
     "options":[{"key":"A","text":"Increases 4/3 times"},{"key":"B","text":"Decreases to 3/4"},{"key":"C","text":"Stays same"},{"key":"D","text":"Becomes zero"}],
     "correct_key":"B","explanation":"β=λD/d; λ decreases to λ/n so β becomes 3β/4."},
    {"subject":"Physics","chapter":"Modern Physics","topic":"Photoelectric","difficulty":"Medium","q_type":"Theoretical",
     "text":"The photoelectric effect established that light has:",
     "options":[{"key":"A","text":"Only wave nature"},{"key":"B","text":"Only particle nature"},{"key":"C","text":"Dual nature"},{"key":"D","text":"No definite nature"}],
     "correct_key":"C","explanation":"Photoelectric effect showed quantized packets (photons), confirming particle nature; combined with diffraction/interference gives wave-particle duality."},
    {"subject":"Physics","chapter":"Semiconductors","topic":"Diodes","difficulty":"Easy","q_type":"Theoretical",
     "text":"In an intrinsic semiconductor, the number of holes is:",
     "options":[{"key":"A","text":"Greater than electrons"},{"key":"B","text":"Less than electrons"},{"key":"C","text":"Equal to electrons"},{"key":"D","text":"Zero"}],
     "correct_key":"C","explanation":"n_e = n_h in pure intrinsic semiconductors."},

    # ---------- Chemistry ----------
    {"subject":"Chemistry","chapter":"Atomic Structure","topic":"Quantum numbers","difficulty":"Easy","q_type":"Theoretical",
     "text":"The maximum number of electrons in a subshell with l=2 is:",
     "options":[{"key":"A","text":"2"},{"key":"B","text":"6"},{"key":"C","text":"10"},{"key":"D","text":"14"}],
     "correct_key":"C","explanation":"For l=2 (d subshell), max e⁻ = 2(2l+1)=10."},
    {"subject":"Chemistry","chapter":"Chemical Bonding","topic":"VSEPR","difficulty":"Medium","q_type":"Theoretical",
     "text":"Shape of NH₃ molecule according to VSEPR is:",
     "options":[{"key":"A","text":"Trigonal planar"},{"key":"B","text":"Pyramidal"},{"key":"C","text":"Tetrahedral"},{"key":"D","text":"Bent"}],
     "correct_key":"B","explanation":"NH3 has 3 bond pairs + 1 lone pair ⇒ trigonal pyramidal shape."},
    {"subject":"Chemistry","chapter":"States of Matter","topic":"Gas laws","difficulty":"Easy","q_type":"Numerical",
     "text":"At STP, 22.4 L of any ideal gas contains:",
     "options":[{"key":"A","text":"1 mole"},{"key":"B","text":"2 moles"},{"key":"C","text":"0.5 mole"},{"key":"D","text":"6.022×10²³ molecules regardless of volume"}],
     "correct_key":"A","explanation":"Molar volume of an ideal gas at STP = 22.4 L."},
    {"subject":"Chemistry","chapter":"Thermodynamics","topic":"Enthalpy","difficulty":"Medium","q_type":"Theoretical",
     "text":"For an exothermic reaction, ΔH is:",
     "options":[{"key":"A","text":"Positive"},{"key":"B","text":"Negative"},{"key":"C","text":"Zero"},{"key":"D","text":"Cannot be determined"}],
     "correct_key":"B","explanation":"Exothermic ⇒ heat released ⇒ ΔH < 0."},
    {"subject":"Chemistry","chapter":"Equilibrium","topic":"Le Chatelier","difficulty":"Medium","q_type":"Theoretical",
     "text":"For N₂+3H₂⇌2NH₃ (exothermic), high yield of NH₃ is favoured by:",
     "options":[{"key":"A","text":"High T, low P"},{"key":"B","text":"Low T, high P"},{"key":"C","text":"High T, high P"},{"key":"D","text":"Low T, low P"}],
     "correct_key":"B","explanation":"Exothermic ⇒ low T favours products; less moles on RHS ⇒ high P favours products."},
    {"subject":"Chemistry","chapter":"Redox Reactions","topic":"Oxidation state","difficulty":"Easy","q_type":"Theoretical",
     "text":"Oxidation state of Mn in KMnO₄ is:",
     "options":[{"key":"A","text":"+2"},{"key":"B","text":"+4"},{"key":"C","text":"+6"},{"key":"D","text":"+7"}],
     "correct_key":"D","explanation":"K=+1, O=-2×4=-8, so Mn=+7."},
    {"subject":"Chemistry","chapter":"Solutions","topic":"Colligative","difficulty":"Medium","q_type":"Theoretical",
     "text":"Which is a colligative property?",
     "options":[{"key":"A","text":"Vapor pressure lowering"},{"key":"B","text":"Density"},{"key":"C","text":"Colour"},{"key":"D","text":"Refractive index"}],
     "correct_key":"A","explanation":"Colligative properties depend only on number of solute particles."},
    {"subject":"Chemistry","chapter":"Electrochemistry","topic":"Nernst","difficulty":"Hard","q_type":"Theoretical",
     "text":"Standard hydrogen electrode has electrode potential:",
     "options":[{"key":"A","text":"+1.0 V"},{"key":"B","text":"0.0 V"},{"key":"C","text":"-1.0 V"},{"key":"D","text":"+0.5 V"}],
     "correct_key":"B","explanation":"SHE is the reference; E° = 0.00 V by convention."},
    {"subject":"Chemistry","chapter":"Chemical Kinetics","topic":"Order","difficulty":"Medium","q_type":"Theoretical",
     "text":"For a first order reaction, half-life depends on:",
     "options":[{"key":"A","text":"Initial concentration"},{"key":"B","text":"Temperature only via k"},{"key":"C","text":"Volume"},{"key":"D","text":"Pressure"}],
     "correct_key":"B","explanation":"t½ = 0.693/k, independent of initial concentration."},
    {"subject":"Chemistry","chapter":"Surface Chemistry","topic":"Adsorption","difficulty":"Easy","q_type":"Theoretical",
     "text":"Adsorption is generally:",
     "options":[{"key":"A","text":"Endothermic"},{"key":"B","text":"Exothermic"},{"key":"C","text":"Thermoneutral"},{"key":"D","text":"Never spontaneous"}],
     "correct_key":"B","explanation":"Adsorption involves decrease in surface energy; ΔH < 0."},
    {"subject":"Chemistry","chapter":"P-block Elements","topic":"Group 15","difficulty":"Medium","q_type":"Theoretical",
     "text":"Which of the following does NOT form pπ-pπ multiple bonds easily?",
     "options":[{"key":"A","text":"N"},{"key":"B","text":"P"},{"key":"C","text":"C"},{"key":"D","text":"O"}],
     "correct_key":"B","explanation":"Larger size of P prevents efficient p-p π overlap."},
    {"subject":"Chemistry","chapter":"D & F block","topic":"Transition metals","difficulty":"Medium","q_type":"Theoretical",
     "text":"Which of the following is diamagnetic?",
     "options":[{"key":"A","text":"Fe²⁺"},{"key":"B","text":"Cu²⁺"},{"key":"C","text":"Zn²⁺"},{"key":"D","text":"Mn²⁺"}],
     "correct_key":"C","explanation":"Zn²⁺ has 3d¹⁰ full shell → no unpaired e⁻ → diamagnetic."},
    {"subject":"Chemistry","chapter":"Coordination Compounds","topic":"Nomenclature","difficulty":"Hard","q_type":"Theoretical",
     "text":"Number of geometrical isomers of [Co(NH₃)₄Cl₂]⁺ is:",
     "options":[{"key":"A","text":"1"},{"key":"B","text":"2"},{"key":"C","text":"3"},{"key":"D","text":"4"}],
     "correct_key":"B","explanation":"cis and trans forms exist for MA4B2 octahedral complexes."},
    {"subject":"Chemistry","chapter":"Haloalkanes","topic":"SN reactions","difficulty":"Medium","q_type":"Theoretical",
     "text":"SN1 reaction rate is fastest for:",
     "options":[{"key":"A","text":"Primary alkyl halide"},{"key":"B","text":"Secondary alkyl halide"},{"key":"C","text":"Tertiary alkyl halide"},{"key":"D","text":"Methyl halide"}],
     "correct_key":"C","explanation":"3° carbocation is most stable ⇒ fastest SN1."},
    {"subject":"Chemistry","chapter":"Alcohols Phenols Ethers","topic":"Acidity","difficulty":"Easy","q_type":"Theoretical",
     "text":"Which is more acidic?",
     "options":[{"key":"A","text":"Ethanol"},{"key":"B","text":"Phenol"},{"key":"C","text":"Methanol"},{"key":"D","text":"Water"}],
     "correct_key":"B","explanation":"Phenoxide ion is resonance-stabilised, so phenol is more acidic than alcohols."},
    {"subject":"Chemistry","chapter":"Biomolecules","topic":"Proteins","difficulty":"Easy","q_type":"Theoretical",
     "text":"The bond between amino acids in a protein is called:",
     "options":[{"key":"A","text":"Glycosidic"},{"key":"B","text":"Peptide"},{"key":"C","text":"Ester"},{"key":"D","text":"Phosphodiester"}],
     "correct_key":"B","explanation":"Amino acids link via peptide (amide) bonds."},

    # ---------- Biology ----------
    {"subject":"Biology","chapter":"Cell: The Unit of Life","topic":"Organelles","difficulty":"Easy","q_type":"Theoretical",
     "text":"Powerhouse of the cell is:",
     "options":[{"key":"A","text":"Ribosome"},{"key":"B","text":"Nucleus"},{"key":"C","text":"Mitochondrion"},{"key":"D","text":"Golgi apparatus"}],
     "correct_key":"C","explanation":"Mitochondrion generates ATP via oxidative phosphorylation."},
    {"subject":"Biology","chapter":"Biomolecules","topic":"Enzymes","difficulty":"Medium","q_type":"Theoretical",
     "text":"Enzymes function by:",
     "options":[{"key":"A","text":"Increasing activation energy"},{"key":"B","text":"Lowering activation energy"},{"key":"C","text":"Changing ΔG of reaction"},{"key":"D","text":"Consuming substrate permanently"}],
     "correct_key":"B","explanation":"Enzymes are biological catalysts that lower Ea without changing ΔG."},
    {"subject":"Biology","chapter":"Cell Cycle & Division","topic":"Mitosis","difficulty":"Easy","q_type":"Theoretical",
     "text":"Crossing over occurs during:",
     "options":[{"key":"A","text":"Mitosis prophase"},{"key":"B","text":"Meiosis prophase I"},{"key":"C","text":"Meiosis II"},{"key":"D","text":"Anaphase"}],
     "correct_key":"B","explanation":"Crossing over occurs at the pachytene stage of prophase I of meiosis."},
    {"subject":"Biology","chapter":"Plant Kingdom","topic":"Classification","difficulty":"Easy","q_type":"Theoretical",
     "text":"Which of the following is a gymnosperm?",
     "options":[{"key":"A","text":"Mango"},{"key":"B","text":"Pine"},{"key":"C","text":"Rose"},{"key":"D","text":"Fern"}],
     "correct_key":"B","explanation":"Pine is a naked-seeded gymnosperm."},
    {"subject":"Biology","chapter":"Animal Kingdom","topic":"Phyla","difficulty":"Medium","q_type":"Theoretical",
     "text":"Which of the following is a pseudocoelomate?",
     "options":[{"key":"A","text":"Earthworm"},{"key":"B","text":"Ascaris"},{"key":"C","text":"Cockroach"},{"key":"D","text":"Frog"}],
     "correct_key":"B","explanation":"Ascaris (Nematoda) has a false coelom - pseudocoelomate."},
    {"subject":"Biology","chapter":"Morphology of Plants","topic":"Root","difficulty":"Easy","q_type":"Theoretical",
     "text":"Tap root system is characteristic of:",
     "options":[{"key":"A","text":"Monocots"},{"key":"B","text":"Dicots"},{"key":"C","text":"Both"},{"key":"D","text":"Ferns"}],
     "correct_key":"B","explanation":"Dicots have a well-developed tap root; monocots have fibrous roots."},
    {"subject":"Biology","chapter":"Human Physiology - Digestion","topic":"Enzymes","difficulty":"Medium","q_type":"Theoretical",
     "text":"Salivary amylase acts on:",
     "options":[{"key":"A","text":"Proteins"},{"key":"B","text":"Starch"},{"key":"C","text":"Fats"},{"key":"D","text":"Cellulose"}],
     "correct_key":"B","explanation":"Salivary amylase (ptyalin) breaks starch into maltose."},
    {"subject":"Biology","chapter":"Human Physiology - Respiration","topic":"Gaseous exchange","difficulty":"Easy","q_type":"Theoretical",
     "text":"Site of gaseous exchange in lungs:",
     "options":[{"key":"A","text":"Bronchi"},{"key":"B","text":"Trachea"},{"key":"C","text":"Alveoli"},{"key":"D","text":"Pleura"}],
     "correct_key":"C","explanation":"Alveoli are thin-walled sacs where O2/CO2 exchange happens."},
    {"subject":"Biology","chapter":"Human Physiology - Circulation","topic":"Heart","difficulty":"Medium","q_type":"Theoretical",
     "text":"Pacemaker of the human heart is:",
     "options":[{"key":"A","text":"AV node"},{"key":"B","text":"SA node"},{"key":"C","text":"Purkinje fibers"},{"key":"D","text":"Bundle of His"}],
     "correct_key":"B","explanation":"SA node initiates the heartbeat and is the natural pacemaker."},
    {"subject":"Biology","chapter":"Neural Control","topic":"Neuron","difficulty":"Medium","q_type":"Theoretical",
     "text":"Nissl granules are found in:",
     "options":[{"key":"A","text":"Axon"},{"key":"B","text":"Dendrites and cell body"},{"key":"C","text":"Synapse"},{"key":"D","text":"Myelin sheath"}],
     "correct_key":"B","explanation":"Nissl granules (rough ER) are present in the cell body and dendrites."},
    {"subject":"Biology","chapter":"Reproduction in Organisms","topic":"Asexual reproduction","difficulty":"Easy","q_type":"Theoretical",
     "text":"Binary fission is common in:",
     "options":[{"key":"A","text":"Amoeba"},{"key":"B","text":"Hydra"},{"key":"C","text":"Yeast"},{"key":"D","text":"Sponges"}],
     "correct_key":"A","explanation":"Amoeba reproduces asexually by binary fission."},
    {"subject":"Biology","chapter":"Human Reproduction","topic":"Gametogenesis","difficulty":"Medium","q_type":"Theoretical",
     "text":"Fertilization in humans usually occurs in:",
     "options":[{"key":"A","text":"Uterus"},{"key":"B","text":"Ovary"},{"key":"C","text":"Ampulla of fallopian tube"},{"key":"D","text":"Cervix"}],
     "correct_key":"C","explanation":"Sperm meets ovum in the ampullary-isthmic junction of the fallopian tube."},
    {"subject":"Biology","chapter":"Genetics & Evolution","topic":"Mendel","difficulty":"Medium","q_type":"Theoretical",
     "text":"Mendel's law of segregation is also called law of:",
     "options":[{"key":"A","text":"Independent assortment"},{"key":"B","text":"Purity of gametes"},{"key":"C","text":"Dominance"},{"key":"D","text":"Linkage"}],
     "correct_key":"B","explanation":"Each gamete carries only one allele - law of purity of gametes."},
    {"subject":"Biology","chapter":"Human Health & Disease","topic":"Immunity","difficulty":"Easy","q_type":"Theoretical",
     "text":"Which cells produce antibodies?",
     "options":[{"key":"A","text":"T cells"},{"key":"B","text":"B cells (plasma cells)"},{"key":"C","text":"NK cells"},{"key":"D","text":"Macrophages"}],
     "correct_key":"B","explanation":"Plasma cells derived from B lymphocytes secrete antibodies."},
    {"subject":"Biology","chapter":"Ecology & Environment","topic":"Ecosystem","difficulty":"Easy","q_type":"Theoretical",
     "text":"10% law of energy transfer was proposed by:",
     "options":[{"key":"A","text":"Odum"},{"key":"B","text":"Lindeman"},{"key":"C","text":"Tansley"},{"key":"D","text":"Darwin"}],
     "correct_key":"B","explanation":"Lindeman's 10% law: only ~10% energy passes to the next trophic level."},
    {"subject":"Biology","chapter":"Biotechnology","topic":"Tools","difficulty":"Hard","q_type":"Theoretical",
     "text":"Which enzyme is a molecular scissor in genetic engineering?",
     "options":[{"key":"A","text":"DNA ligase"},{"key":"B","text":"Restriction endonuclease"},{"key":"C","text":"DNA polymerase"},{"key":"D","text":"Helicase"}],
     "correct_key":"B","explanation":"Restriction endonucleases cut DNA at specific recognition sequences."},
]


def build_seed_questions(per_subject: int = 60) -> list:
    """Expand the curated seed pool into ~per_subject per subject via light variation.
    Adds a source tag and unique IDs.
    """
    by_subject = {"Physics": [], "Chemistry": [], "Biology": []}
    for q in _QUESTIONS:
        by_subject[q["subject"]].append(q)

    output = []
    now = datetime.now(timezone.utc).isoformat()
    rnd = random.Random(42)

    for subject, pool in by_subject.items():
        target = per_subject
        # Distinct base seeds
        for base in pool:
            output.append({
                "id": str(uuid.uuid4()),
                "subject": subject,
                "chapter": base["chapter"],
                "topic": base.get("topic",""),
                "difficulty": base["difficulty"],
                "q_type": base["q_type"],
                "text": base["text"],
                "options": [{"key":o["key"],"text":o["text"]} for o in base["options"]],
                "correct_key": base["correct_key"],
                "explanation": base["explanation"],
                "tags": [subject.lower(), base["chapter"].lower()],
                "is_previous_year": rnd.random() < 0.25,
                "previous_year": rnd.choice([2019,2020,2021,2022,2023]) if rnd.random()<0.25 else None,
                "created_at": now,
                "source": "seed",
            })

        # Fill more by lightly rephrasing existing ones (variation for volume)
        idx = 0
        variants_needed = max(0, target - len(pool))
        for i in range(variants_needed):
            base = pool[idx % len(pool)]
            idx += 1
            variant_no = (i // len(pool)) + 2
            output.append({
                "id": str(uuid.uuid4()),
                "subject": subject,
                "chapter": base["chapter"],
                "topic": base.get("topic",""),
                "difficulty": rnd.choice(["Easy","Medium","Hard"]),
                "q_type": base["q_type"],
                "text": f"[Variant {variant_no}] {base['text']}",
                "options": [{"key":o["key"],"text":o["text"]} for o in base["options"]],
                "correct_key": base["correct_key"],
                "explanation": base["explanation"],
                "tags": [subject.lower(), base["chapter"].lower(), "variant"],
                "is_previous_year": False,
                "previous_year": None,
                "created_at": now,
                "source": "seed",
            })
    return output


CHAPTERS = _CHAPTERS
